web:
  image: nginx
  ports:
    - "8383:80"
  volumes:
    - ./data/sites:/var/www
    - ./data/php5:/etc/php5
    - ./data/nginx/sites:/etc/nginx/sites-enabled
  environment:
    - ALLOW_OVERRIDE=true

  links:
    - db:db

db:
  image: mysql
  # volumes:
  #   - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
