web:
    restart: always
    build: ./../sources/web
    environment:
        USEPHP: true
        USEPHALCON: false
    ports:
        - "80:80"
    volumes:
        - ./../data/nginx/logs:/var/log/nginx
        - ./../data/nginx/etc:/etc/nginx
        - ./../data/nginx/var/www/html:/var/www/html
    links:
        - php:php

php:
    restart: always
    build: ./../sources/php-fpm
    volumes:
        - ./../data/php5-fpm/etc:/etc/php5
        - ./../data/php5-fpm/logs:/var/log
        - ./../data/nginx/var/www/html:/var/www/html
    ports:
        - "9200:9200"
    links:
        - db:db
        - memcached:memcached

memcached:
    image: memcached
    ports: 
        - 11211

db:
    image: mysql
    volumes:
        - ./../data/mysql/data:/var/lib/mysql
        - ./../data/mysql/logs:/var/log/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=ngooxav
        - MYSQL_DATABASE=devdb
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=coders
