web:
    environment:
        USEPHP: true
    image: webofmars/nginx
    ports:
        - "80:80"
    volumes:
        - ../data/nginx/logs:/var/log/nginx
        - ../data/nginx/etc:/etc/nginx
        - ../data/nginx/var/www/html:/var/www/html
    links:
        - php:php

php:
    image: webofmars/php-fpm-phalcon
    volumes:
        - ../data/php5-fpm-phalcon/etc:/etc/php5
        - ../data/php5-fpm-phalcon/logs:/var/log
        - ../data/nginx/var/www/html:/var/www/html
    ports:
        - "9200:9200"
    links:
        - db:db

db:
    image: mysql
    volumes:
        - ../data/mysql/data:/var/lib/mysql
        - ../data/mysql/logs:/var/log/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=ngooxav
        - MYSQL_DATABASE=devdb
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=coders
