web:
    restart: always
    build: ./../sources/web
    environment:
        USEPHP: 'false'
        USEPHALCON: 'true'
    ports:
        - "80:80"
    volumes:
        - ./../data/nginx/logs:/var/log/nginx
        - ./../data/nginx/etc:/etc/nginx
        - ./../data/nginx/var/www/html:/var/www/html
    links:
        - php:php

php:
    restart: always
    build: ./../sources/php-fpm-phalcon
    volumes:
        - ./../data/php5-fpm-phalcon/etc:/etc/php5
        - ./../data/php5-fpm-phalcon/logs:/var/log
        - ./../data/nginx/var/www/html:/var/www/html
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
        - BLACKFIRE_LOG_LEVEL
    ports:
        - "9000:9000"
    links:
        - db:db
        - memcached:memcached
        - maildev:maildev
        - blackfire:blackfire

memcached:
    restart: always
    image: memcached
    ports: 
        - 11211

db:
    restart: always
    image: mysql
    volumes:
        - ./../data/mysql/data:/var/lib/mysql
        - ./../data/mysql/logs:/var/log/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=ngooxav
        - MYSQL_DATABASE=devdb
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=coders

maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
        - "1080:80"

blackfire:
    restart: always
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_CLIENT_ID
        - BLACKFIRE_CLIENT_TOKEN
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
        - BLACKFIRE_LOG_LEVEL
