web:
    restart: always
    build: ./../sources/web
    environment:
        USEPHP: false 
        USEPHALCON: true 
    ports:
        - "80:80"
    volumes:
        - ./../data/nginx/logs:/var/log/nginx
        - ./../data/nginx/etc:/etc/nginx
        - ./../data/nginx/var/www/html:/var/www/html
    links:
        - phalcon:php

phalcon:
    restart: always
    build: ./../sources/php-fpm-phalcon
    volumes:
        - ./../data/php5-fpm-phalcon/etc:/etc/php5
        - ./../data/php5-fpm-phalcon/logs:/var/log
        - ./../data/nginx/var/www/html:/var/www/html
    ports:
        - "9200:9200"
    links:
        - memcached:memcached
        - maildev:maildev

memcached:
    image: memcached
    ports: 
        - 11211

maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
        - "1080:80"
