web:
    environment:
        USEPHP: false 
        USEPHALCON: true 
    image: webofmars/nginx
    ports:
        - "80:80"
    volumes:
        - ./../data/nginx/logs:/var/log/nginx
        - ./../data/nginx/etc:/etc/nginx
        - ./../data/nginx/var/www/html:/var/www/html
    links:
        - phalcon:php

phalcon:
    labels:
        'com.docker.compose.project': 'lempdev'
    image: webofmars/php-fpm-phalcon
    volumes:
        - ./../data/php5-fpm-phalcon/etc:/etc/php5
        - ./../data/php5-fpm-phalcon/logs:/var/log
        - ./../data/nginx/var/www/html:/var/www/html
    ports:
        - "9200:9200"
